name: Deploy ChatAppInfrastructure App

on:
  push:
    branches:
      - main
      - production

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/ChatAppInfra

      - name: Build the application
        run: dotnet build --configuration Release --no-restore
        working-directory: src/ChatAppInfra

      - name: Build Lambda functions
        run: |
          echo "Building Lambda: GetUploadUrlLambda"
          dotnet publish lambda/GetUploadUrlLambda/GetUploadUrlLambda.csproj \
            -c Release \
            -o lambda/GetUploadUrlLambda/bin/Release/net8.0/publish

          echo "Building Lambda: ImageModerationLambda"
          dotnet publish lambda/ImageModerationLambda/ImageModerationLambda.csproj \
            -c Release \
            -o lambda/ImageModerationLambda/bin/Release/net8.0/publish

          

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Bootstrap
        run: cdk bootstrap

      - name: CDK Diff Dev
        run: cdk diff -c environment=dev

      - name: Deploy Dev
        run: cdk deploy -c environment=dev --require-approval never


  deploy-prod:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/ChatAppInfra

      - name: Build the application
        run: dotnet build --configuration Release --no-restore
        working-directory: src/ChatAppInfra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Diff Prod
        run: cdk diff -c environment=prod

      - name: Deploy Prod
        run: cdk deploy -c environment=prod --require-approval never