name: Deploy ChatAppInfrastructure App

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: write

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/ChatAppInfra

      - name: Build the application
        run: dotnet build --configuration Release --no-restore
        working-directory: src/ChatAppInfra

      - name: Build Lambda functions
        run: |
          echo "Building Lambda: GetUploadUrlLambda"
          dotnet publish lambda/GetUploadUrlLambda/GetUploadUrlLambda.csproj \
            -c Release \
            -o lambda/GetUploadUrlLambda/bin/Release/net8.0/publish

          echo "Building Lambda: ImageModerationLambda"
          dotnet publish lambda/ImageModerationLambda/ImageModerationLambda.csproj \
            -c Release \
            -o lambda/ImageModerationLambda/bin/Release/net8.0/publish

          echo "Building Lambda: LinkPreviewLambda"
          dotnet publish lambda/LinkPreview/LinkPreviewLambda/LinkPreviewLambda.csproj \
            -c Release \
            -o lambda/LinkPreview/LinkPreviewLambda/bin/Release/net8.0/publish

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Bootstrap
        run: cdk bootstrap

      - name: CDK Diff Dev
        run: cdk diff -c environment=dev

      - name: Generate Version
        id: version
        run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

      - name: Deploy Dev
        run: cdk deploy -c environment=dev -c version=${{ env.VERSION }} --require-approval never

      - name: Create Git Tag
        run: |
          git fetch --tags
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}


  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/ChatAppInfra

      - name: Build the application
        run: dotnet build --configuration Release --no-restore
        working-directory: src/ChatAppInfra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Diff Prod
        run: cdk diff -c environment=prod
      - name: Generate Version
        id: version
        run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

 


      - name: Deploy Prod
        run: cdk deploy -c environment=prod -c version=${{ env.VERSION }} --require-approval never

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}